server:
    port: 8081

spring:
    datasource:
        driverClassName: org.h2.Driver
        # url: jdbc:h2:file:./.h2/monitordb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;DATABASE_TO_UPPER=FALSE;
        url: jdbc:h2:mem:monitordb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=FALSE;
        username: sa
        password:
    h2.console:
        enabled: true
        path: /h2
    jpa:
        generateDdl: true
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
        showSql: true
    thymeleaf:
        cache: false

logging:
    file: monitor.log
    level:
        org.springframework: INFO
        online.zhaopei.monitor: TRACE
